---
title: "Assignment #2"
format: html
editor: visual
---

```{r}

{r setup, include=FALSE}
knitr::opts_chunk$set(echo       = TRUE, 
                      fig.height = 3, 
                      fig.width  = 6,
                      fig.align  = "center")
ggplot2::theme_set(ggplot2::theme_bw())



```

```{r}

#| message: false
library(tidyverse)

library(lubridate)


```

## If statement included

```{r}


pos_na <- function(a,b){

if(length(a) == length(b)) 
  
{which (is.na(a) & is.na(b))}

else {print("The vectors are not the same length.")}
}


```

```{r}



x <- c(1, NA, 2) 
y <- c(NA, NA)
pos_na(x,y)
```

```{r}

a <- c(NA, NA, 2) 
b <- c(NA, NA, 2)
pos_na(a,b)


```

```{r}


c <- c(NA, 5, NA) 
d <- c(NA, NA, NA)
pos_na(c,d)


```

```{r}

e <- c(NA, NA, NA, 2, NA, 4, NA)
f <- c(NA, NA, 2, 4, 4, NA, NA)

pos_na(e,f)



```

```{r}

g <- c(1, NA, NA, 2, NA, 4, NA)
h <- c(NA, -5, 2, 4, 4, NA, 11)

pos_na(g,h)

```

```{r}





```

```{r}





```

```{r}






```

## Question 3

```{r}

V <- c("Bears", "Lions", "Dolphins", "Eagles", "Bengals")


names(V) <- c("b", "l", "d", "e", "be")

V[c("b", "d", "be")]

```

## Subsetting with for loop

```{r}

#Subsetting for loop

V[c("b", "b", "b")]





```

## Subsetting with positive indices

```{r}

V <- c("Bears", "Lions", "Dolphins", "Eagles", "Bengals")


names(V) <- c(1, 2, 3, 4, 5)

V[c(1, 2, 3, 4, 5)]






```

## Subsetting using negative indices 

```{r}


V <- c("Bears", "Lions", "Dolphins", "Eagles", "Bengals")


names(V) <- c(1, 2, 3, 4, 5)


V[-c(1,2,3,4,5)]

print(V)

```

## Subsetting using logical indexing

```{r}






```
